# Assignment Day 3

In [1]:
# Questions 1: 
# Create a numpy array starting from 2 till 50 with a stepsize of 3. 

import numpy as np

arr=np.arange(2,50,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


In [2]:
# Questions 2:
# Accept two lists of 5 elements each from the user.
# Convert them to numpy arrays.
# Concatenate these arrays and print it. Also sort these arrays and print it.

import numpy as np

lst1 = []
lst2 = []

print("Enter 5 elements for list 1")
for i in range(0, 5):   
    ele = int(input())   
    lst1.append(ele)    
print("list 1 is : ",lst1)
print()
 
print("Enter 5 elements for list 2")
for i in range(0, 5):    
    ele = int(input())   
    lst2.append(ele)
print("list 2 is : ",lst2)
print()

arr1=np.array(lst1)
arr2=np.array(lst2)

print("After concatenate")
arr3=np.concatenate((arr1,arr2))
print(arr3)
print()

print("After sorting")
print(np.sort(arr3))

Enter 5 elements for list 1
1
3
5
7
9
list 1 is :  [1, 3, 5, 7, 9]

Enter 5 elements for list 2
2
4
6
8
10
list 2 is :  [2, 4, 6, 8, 10]

After concatenate
[ 1  3  5  7  9  2  4  6  8 10]

After sorting
[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
# Questions 3: 
# Write a code snippet to find the dimensions of a ndarray and its size.

import numpy as np

arr=np.array([[1,2,3],[2,3,4],[3,4,5]])

print("The dimensions of a ndarray is : ",arr.ndim)
print("Size if ndarray is :",arr.size)

The dimensions of a ndarray is :  2
Size if ndarray is : 9


In [ ]:
# Questions 4: 
# How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
# Hint: np.newaxis, np.expand_dims 

import numpy as np 

#1d Array
arr_1d= np.array()